name: ✨ 功能请求
description: 提议一个新功能
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！请详细描述您的需求。

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请清晰地描述您希望实现的功能
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能解决了什么问题？
      placeholder: 我在使用 [...] 时感到困扰...

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您希望如何实现这个功能？
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 您考虑过的其他解决方案

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      options:
        - 高 - 严重影响使用
        - 中 - 有此功能会更好
        - 低 - 锦上添花
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 其他可能有用的信息或截图
